### ISSUE TITLE
Crash on BBPlayer.m line 996 `-[BBPlayer evaluateJavaScriptSynchronous:]` when app is in background

### ISSUE THREAD

**Issue by jhildensperger** [bluebillywig/playerSdkLibraries#6] opened 2021-06-15 08:30 UTC
- BlueBillywigPlayerSDK (1.4.1.27)

<img width="429" alt="Screenshot 2021-06-15 at 10 28 10" src="https://user-images.githubusercontent.com/685326/122019795-74b16900-cdc4-11eb-8d83-cbf0f4ea2e7b.png">

```
Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x1aab37754 __exceptionPreprocess
1  libobjc.A.dylib                0x1bf5fe7a8 objc_exception_throw
2  CoreFoundation                 0x1aaa393f8 -[CFPrefsSearchListSource addManagedSourceForIdentifier:user:]
3  Foundation                     0x1abe60a6c -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:]
4  UIKitCore                      0x1ad009f54 _UIApplicationDrainManagedAutoreleasePool
5  UIKitCore                      0x1ad557e60 _beforeCACommitHandler
6  CoreFoundation                 0x1aaab05e0 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
7  CoreFoundation                 0x1aaaaa704 __CFRunLoopDoObservers
8  CoreFoundation                 0x1aaaaa3b4 CFRunLoopRunSpecific
9  Foundation                     0x1abd97fdc -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
10 BlueBillywigPlayerSDK          0x105e643b4 -[BBPlayer evaluateJavaScriptSynchronous:] + 996 (BBPlayer.m:996)
11 BlueBillywigPlayerSDK          0x105e62c8c -[BBPlayer call:argumentObject:] + 771 (BBPlayer.m:771)
12 BlueBillywigPlayerSDK          0x105e62b1c -[BBPlayer call:arguments:] + 747 (BBPlayer.m:747)
13 BlueBillywigPlayerSDK          0x105e633c4 -[BBPlayer pause] + 855 (BBPlayer.m:855)
```

**Comment by fgroenendijk** [comment] 2021-07-26 14:12
Hello @jhildensperger, we've updated the sdk today (1.4.1.35), and this should be fixed now.

**Closed as completed by fgroenendijk** 2021-07-26 14:12 UTC

**Comment by Yozine** [comment] 2021-10-22 23:17
I was experiencing the same issue (though not in the background) 

The app's build was using version 1.4.1.37. I've since updated to 1.4.1.38 and am testing with that to see whether it is reproducible. 

This is the exception:
```
Fatal Exception: NSInternalInconsistencyException
Invalid parameter not satisfying: [views count] == 3
```

This is the corresponding stack trace: 
```
Fatal Exception: NSInternalInconsistencyException
0   CoreFoundation                 0x11b25c __exceptionPreprocess
1   libobjc.A.dylib                0x26480 objc_exception_throw
2   CoreFoundation                 0x28c98 -[CFPrefsSearchListSource addManagedSourceForIdentifier:user:]
3   Foundation                     0x77ef8 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4   UIKitCore                      0x3da8c4 -[_UIQueuingScrollView _replaceViews:updatingContents:adjustContentInsets:animated:]
5   UIKitCore                      0x3dd7dc -[_UIQueuingScrollView _didScrollWithAnimation:force:]
6   UIKitCore                      0x3d9b00 -[_UIQueuingScrollView layoutSubviews]
7   UIKitCore                      0x102f8bc -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
8   QuartzCore                     0x15e424 -[CALayer layoutSublayers]
9   QuartzCore                     0x164bac CA::Layer::layout_if_needed(CA::Transaction*)
10  QuartzCore                     0x17016c CA::Layer::layout_and_display_if_needed(CA::Transaction*)
11  QuartzCore                     0xb8578 CA::Context::commit_transaction(CA::Transaction*, double, double*)
12  QuartzCore                     0xe32c8 CA::Transaction::commit()
13  QuartzCore                     0xe4530 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*)
14  CoreFoundation                 0x99540 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
15  CoreFoundation                 0x93b70 __CFRunLoopDoObservers
16  CoreFoundation                 0x93824 CFRunLoopRunSpecific
17  Foundation                     0x7e64 -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
18  TFPresentation                 0x1e3ad4 -[BBPlayer evaluateJavaScriptSynchronous:] + 1039 (BBPlayer.m:1039)
19  TFPresentation                 0x1e2058 -[BBPlayer call:argumentObject:] + 809 (BBPlayer.m:809)
20  TFPresentation                 0x1e0f58 -[BBPlayer userContentController:didReceiveScriptMessage:] + 660 (BBPlayer.m:660)
21  WebKit                         0x253d04 ScriptMessageHandlerDelegate::didPostMessage(WebKit::WebPageProxy&, WebKit::FrameInfoData&&, API::ContentWorld&, WebCore::SerializedScriptValue&)
22  WebKit                         0x4501e8 WebKit::WebUserContentControllerProxy::didPostMessage(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long long, IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::CompletionHandler<void (IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::String const&)>&&)
23  WebKit                         0x6aba9c void IPC::handleMessageAsync<Messages::WebUserContentControllerProxy::DidPostMessage, WebKit::WebUserContentControllerProxy, void (WebKit::WebUserContentControllerProxy::*)(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long long, IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::CompletionHandler<void (IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::String const&)>&&)>(IPC::Connection&, IPC::Decoder&, WebKit::WebUserContentControllerProxy*, void (WebKit::WebUserContentControllerProxy::*)(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long long, IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::CompletionHandler<void (IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::String const&)>&&))
24  WebKit                         0x6ab180 WebKit::WebUserContentControllerProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&)
25  WebKit                         0x4dd90 IPC::MessageReceiverMap::dispatchMessage(IPC::Connection&, IPC::Decoder&)
26  WebKit                         0x3a0060 WebKit::WebProcessProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&)
27  WebKit                         0x301b4 IPC::Connection::dispatchMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decoder> >)
28  WebKit                         0x2fb80 IPC::Connection::dispatchIncomingMessages()
29  JavaScriptCore                 0xe70038 WTF::RunLoop::performWork()
30  JavaScriptCore                 0xe70e30 WTF::RunLoop::performWork(void*)
31  CoreFoundation                 0x9a8a8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
32  CoreFoundation                 0x9a7a8 __CFRunLoopDoSource0
33  CoreFoundation                 0x99afc __CFRunLoopDoSources0
34  CoreFoundation                 0x94018 __CFRunLoopRun
35  CoreFoundation                 0x937d0 CFRunLoopRunSpecific
36  Foundation                     0x7e64 -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
37  TFPresentation                 0x1e3ad4 -[BBPlayer evaluateJavaScriptSynchronous:] + 1039 (BBPlayer.m:1039)
38  TFPresentation                 0x1e2058 -[BBPlayer call:argumentObject:] + 809 (BBPlayer.m:809)
39  TFPresentation                 0x1e0f58 -[BBPlayer userContentController:didReceiveScriptMessage:] + 660 (BBPlayer.m:660)
40  WebKit                         0x253d04 ScriptMessageHandlerDelegate::didPostMessage(WebKit::WebPageProxy&, WebKit::FrameInfoData&&, API::ContentWorld&, WebCore::SerializedScriptValue&)
41  WebKit                         0x4501e8 WebKit::WebUserContentControllerProxy::didPostMessage(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long long, IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::CompletionHandler<void (IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::String const&)>&&)
42  WebKit                         0x6aba9c void IPC::handleMessageAsync<Messages::WebUserContentControllerProxy::DidPostMessage, WebKit::WebUserContentControllerProxy, void (WebKit::WebUserContentControllerProxy::*)(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long long, IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::CompletionHandler<void (IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::String const&)>&&)>(IPC::Connection&, IPC::Decoder&, WebKit::WebUserContentControllerProxy*, void (WebKit::WebUserContentControllerProxy::*)(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long long, IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::CompletionHandler<void (IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::String const&)>&&))
43  WebKit                         0x6ab180 WebKit::WebUserContentControllerProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&)
44  WebKit                         0x4dd90 IPC::MessageReceiverMap::dispatchMessage(IPC::Connection&, IPC::Decoder&)
45  WebKit                         0x3a0060 WebKit::WebProcessProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&)
46  WebKit                         0x301b4 IPC::Connection::dispatchMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decoder> >)
47  WebKit                         0x2fb80 IPC::Connection::dispatchIncomingMessages()
48  JavaScriptCore                 0xe70038 WTF::RunLoop::performWork()
49  JavaScriptCore                 0xe70e30 WTF::RunLoop::performWork(void*)
50  CoreFoundation                 0x9a8a8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
51  CoreFoundation                 0x9a7a8 __CFRunLoopDoSource0
52  CoreFoundation                 0x99afc __CFRunLoopDoSources0
53  CoreFoundation                 0x94018 __CFRunLoopRun
54  CoreFoundation                 0x937d0 CFRunLoopRunSpecific
55  Foundation                     0x7e64 -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
56  TFPresentation                 0x1e3ad4 -[BBPlayer evaluateJavaScriptSynchronous:] + 1039 (BBPlayer.m:1039)
57  TFPresentation                 0x1e07b8 -[BBPlayer userContentController:didReceiveScriptMessage:] + 553 (BBPlayer.m:553)
58  WebKit                         0x253d04 ScriptMessageHandlerDelegate::didPostMessage(WebKit::WebPageProxy&, WebKit::FrameInfoData&&, API::ContentWorld&, WebCore::SerializedScriptValue&)
59  WebKit                         0x4501e8 WebKit::WebUserContentControllerProxy::didPostMessage(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long long, IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::CompletionHandler<void (IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::String const&)>&&)
60  WebKit                         0x6aba9c void IPC::handleMessageAsync<Messages::WebUserContentControllerProxy::DidPostMessage, WebKit::WebUserContentControllerProxy, void (WebKit::WebUserContentControllerProxy::*)(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long long, IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::CompletionHandler<void (IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::String const&)>&&)>(IPC::Connection&, IPC::Decoder&, WebKit::WebUserContentControllerProxy*, void (WebKit::WebUserContentControllerProxy::*)(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long long, IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::CompletionHandler<void (IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::String const&)>&&))
61  WebKit                         0x6ab180 WebKit::WebUserContentControllerProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&)
62  WebKit                         0x4dd90 IPC::MessageReceiverMap::dispatchMessage(IPC::Connection&, IPC::Decoder&)
63  WebKit                         0x3a0060 WebKit::WebProcessProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&)
64  WebKit                         0x301b4 IPC::Connection::dispatchMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decoder> >)
65  WebKit                         0x2fb80 IPC::Connection::dispatchIncomingMessages()
66  JavaScriptCore                 0xe70038 WTF::RunLoop::performWork()
67  JavaScriptCore                 0xe70e30 WTF::RunLoop::performWork(void*)
68  CoreFoundation                 0x9a8a8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
69  CoreFoundation                 0x9a7a8 __CFRunLoopDoSource0
70  CoreFoundation                 0x99afc __CFRunLoopDoSources0
71  CoreFoundation                 0x94018 __CFRunLoopRun
72  CoreFoundation                 0x937d0 CFRunLoopRunSpecific
73  Foundation                     0x7e64 -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
74  TFPresentation                 0x1e3ad4 -[BBPlayer evaluateJavaScriptSynchronous:] + 1039 (BBPlayer.m:1039)
75  TFPresentation                 0x1e0730 -[BBPlayer userContentController:didReceiveScriptMessage:] + 551 (BBPlayer.m:551)
76  WebKit                         0x253d04 ScriptMessageHandlerDelegate::didPostMessage(WebKit::WebPageProxy&, WebKit::FrameInfoData&&, API::ContentWorld&, WebCore::SerializedScriptValue&)
77  WebKit                         0x4501e8 WebKit::WebUserContentControllerProxy::didPostMessage(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long long, IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::CompletionHandler<void (IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::String const&)>&&)
78  WebKit                         0x6aba9c void IPC::handleMessageAsync<Messages::WebUserContentControllerProxy::DidPostMessage, WebKit::WebUserContentControllerProxy, void (WebKit::WebUserContentControllerProxy::*)(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long long, IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::CompletionHandler<void (IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::String const&)>&&)>(IPC::Connection&, IPC::Decoder&, WebKit::WebUserContentControllerProxy*, void (WebKit::WebUserContentControllerProxy::*)(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long long, IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::CompletionHandler<void (IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::String const&)>&&))
79  WebKit                         0x6ab180 WebKit::WebUserContentControllerProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&)
80  WebKit                         0x4dd90 IPC::MessageReceiverMap::dispatchMessage(IPC::Connection&, IPC::Decoder&)
81  WebKit                         0x3a0060 WebKit::WebProcessProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&)
82  WebKit                         0x301b4 IPC::Connection::dispatchMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decoder> >)
83  WebKit                         0x2fac8 IPC::Connection::dispatchIncomingMessages()
84  JavaScriptCore                 0xe70038 WTF::RunLoop::performWork()
85  JavaScriptCore                 0xe70e30 WTF::RunLoop::performWork(void*)
86  CoreFoundation                 0x9a8a8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
87  CoreFoundation                 0x9a7a8 __CFRunLoopDoSource0
88  CoreFoundation                 0x99afc __CFRunLoopDoSources0
89  CoreFoundation                 0x94018 __CFRunLoopRun
90  CoreFoundation                 0x937d0 CFRunLoopRunSpecific
91  Foundation                     0x7e64 -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
92  TFPresentation                 0x1e3ad4 -[BBPlayer evaluateJavaScriptSynchronous:] + 1039 (BBPlayer.m:1039)
93  TFPresentation                 0x1e07b8 -[BBPlayer userContentController:didReceiveScriptMessage:] + 553 (BBPlayer.m:553)
94  WebKit                         0x253d04 ScriptMessageHandlerDelegate::didPostMessage(WebKit::WebPageProxy&, WebKit::FrameInfoData&&, API::ContentWorld&, WebCore::SerializedScriptValue&)
95  WebKit                         0x4501e8 WebKit::WebUserContentControllerProxy::didPostMessage(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long long, IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::CompletionHandler<void (IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::String const&)>&&)
96  WebKit                         0x6aba9c void IPC::handleMessageAsync<Messages::WebUserContentControllerProxy::DidPostMessage, WebKit::WebUserContentControllerProxy, void (WebKit::WebUserContentControllerProxy::*)(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long long, IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::CompletionHandler<void (IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::String const&)>&&)>(IPC::Connection&, IPC::Decoder&, WebKit::WebUserContentControllerProxy*, void (WebKit::WebUserContentControllerProxy::*)(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long long, IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::CompletionHandler<void (IPC::ArrayReference<unsigned char, 18446744073709551615ul> const&, WTF::String const&)>&&))
97  WebKit                         0x6ab180 WebKit::WebUserContentControllerProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&)
98  WebKit                         0x4dd90 IPC::MessageReceiverMap::dispatchMessage(IPC::Connection&, IPC::Decoder&)
99  WebKit                         0x3a0060 WebKit::WebProcessProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&)
100 WebKit                         0x301b4 IPC::Connection::dispatchMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decoder> >)
101 WebKit                         0x2fb80 IPC::Connection::dispatchIncomingMessages()
102 JavaScriptCore                 0xe70038 WTF::RunLoop::performWork()
103 JavaScriptCore                 0xe70e30 WTF::RunLoop::performWork(void*)
104 CoreFoundation                 0x9a8a8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
105 CoreFoundation                 0x9a7a8 __CFRunLoopDoSource0
106 CoreFoundation                 0x99b60 __CFRunLoopDoSources0
107 CoreFoundation                 0x94018 __CFRunLoopRun
108 CoreFoundation                 0x937d0 CFRunLoopRunSpecific
109 GraphicsServices               0x3570 GSEventRunModal
110 UIKitCore                      0xb302d0 -[UIApplication _run]
111 UIKitCore                      0xb3584c UIApplicationMain
```

**Comment by jkoppen-bluebillywig** [comment] 2021-11-24 13:16
Hello @Yozine , we've updated the SDK last week (1.4.1.39), and this should be fixed now.
